# Generated by Django 4.0 on 2023-06-28 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_cart", "0001_initial"),
        ("app_item", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_item",
                to="app_item.item",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_add_items",
                to="auth.user",
                verbose_name="покупатель",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(
                related_name="all_items", to="app_cart.CartItem", verbose_name="товар"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_cart",
                to="auth.user",
                verbose_name="покупатель",
            ),
        ),
    ]
