# Generated by Django 4.0 on 2023-07-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_cart", "0003_remove_cart_items_cartitem_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ключ сессии"
            ),
        ),
    ]
