# Generated by Django 4.0 on 2023-07-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_order", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="оплачен"),
        ),
    ]
