# Generated by Django 4.0 on 2023-07-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_order", "0004_alter_orderitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery",
            field=models.CharField(
                choices=[
                    ("standard", "обычная доставка"),
                    ("express", "экспресс доставка"),
                ],
                max_length=20,
                verbose_name="доставка",
            ),
        ),
    ]
